version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:9.2

    working_directory: /tmp/my-project

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run build -- --env=sta

      - run: npm test -- --coverage

      - run:
          name: Build Success
          when: on_success
          command: 'bash <(curl -s https://codecov.io/bash)'

  deploy-job:
      docker:
        - image: circleci/node:9.2

      working_directory: /tmp/my-project

      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

        - run: npm install

        - run: npm run build -- --env=production

        - run:
            name: Deploy Master to Firebase
            command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master